package io.campuscore.restfulapi.thesis.assistant;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;
import org.junit.jupiter.api.Test;

class AssistantOutputGuardTest {

    @Test
    void acceptsNormalAcademicAnswers() {
        assertTrue(AssistantOutputGuard.isSafe("Hạn đăng ký học phần là ngày 15/11/2026."));
        assertTrue(AssistantOutputGuard.isSafe("Mỗi hội đồng bảo vệ gồm từ 03 đến 05 thành viên."));
        assertTrue(AssistantOutputGuard.isSafe("Bạn có thể mở trang Thời khóa biểu để xem lịch học."));
    }

    @Test
    void rejectsCommandsCodeAndImplementationDetails() {
        List<String> leakedOutputs = List.of(
                "```bash\ncurl https://campuscore.local/api/v1/assistant\n```",
                "The retrieved context does not contain API endpoints, curl commands, or Docker Compose instructions.",
                "SELECT * FROM assistant.chat_message;",
                "Exception in thread \"main\" at io.campuscore.Assistant(Assistant.java:42)",
                "The answer was generated by DeepSeek V4 Flash.");

        for (String output : leakedOutputs) {
            assertFalse(AssistantOutputGuard.isSafe(output), output);
        }
    }
}
