package io.campuscore.restfulapi.thesis.assistant;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;
import org.junit.jupiter.api.Test;

class AssistantOutputGuardTest {

    @Test
    void acceptsNormalAcademicAnswers() {
        assertTrue(AssistantOutputGuard.isSafe("Hạn đăng ký học phần là ngày 15/11/2026."));
        assertTrue(AssistantOutputGuard.isSafe("Mỗi hội đồng bảo vệ gồm từ 03 đến 05 thành viên."));
        assertTrue(AssistantOutputGuard.isSafe("Bạn có thể mở trang Thời khóa biểu để xem lịch học."));
    }

    @Test
    void rejectsCommandsCodeAndImplementationDetails() {
        List<String> leakedOutputs = List.of(
                "```bash\ncurl https://campuscore.local/api/v1/assistant\n```",
                "The retrieved context does not contain API endpoints, curl commands, or Docker Compose instructions.",
                "SELECT * FROM assistant.chat_message;",
                "Exception in thread \"main\" at io.campuscore.Assistant(Assistant.java:42)",
                "The answer was generated by DeepSeek V4 Flash.");

        for (String output : leakedOutputs) {
            assertFalse(AssistantOutputGuard.isSafe(output), output);
        }
    }

    /**
     * The SPECIALIZED corpus legitimately teaches CI/CD and REST design, so an
     * answer quoting those strings from the retrieved context is a citation, not
     * a leak. Regression: an unscoped isSafe() check on the provider stream
     * rejected every technical answer, so the specialized mode could never
     * answer its own published topics.
     */
    @Test
    void allowsTechnicalContentThatIsQuotedFromTheApprovedContext() {
        String approvedContext = "CI/CD cho đồ án nên dùng GitHub Actions: mỗi lần push sẽ chạy docker compose up -d --build. "
                + "REST API nên trả về mã 2xx cho thành công. Không chia sẻ api key trong mã nguồn.";

        assertTrue(AssistantOutputGuard.isSafeForAnswer(
                "Bạn có thể dùng GitHub Actions, và chạy lệnh docker compose up -d --build khi push.", approvedContext));
        assertTrue(AssistantOutputGuard.isSafeForAnswer(
                "REST API nên trả về mã 2xx cho thành công, và không nhúng api key vào mã nguồn.", approvedContext));

        // The same strings are still rejected when there is no context to quote from.
        assertFalse(AssistantOutputGuard.isSafeForAnswer(
                "Bạn có thể dùng GitHub Actions, và chạy lệnh docker compose up -d --build khi push.", null));
        assertFalse(AssistantOutputGuard.isSafeForAnswer(
                "Bạn có thể dùng GitHub Actions, và chạy lệnh docker compose up -d --build khi push.", ""));
        // A detail that is NOT in the context stays rejected.
        assertFalse(AssistantOutputGuard.isSafeForAnswer(
                "Chạy psql -h localhost:5432 để xem bảng chat_message.", approvedContext));
        // Code fences stay rejected even when the context has the command: a
        // fence is a formatting leak rather than a quoted phrase.
        assertFalse(AssistantOutputGuard.isSafeForAnswer(
                "```bash\ndocker compose up\n```", approvedContext));
    }

    /**
     * The scope-aware boundary used by RagAssistantGateway for remote-RAG
     * answers: 'specialized' keeps the approved corpus's technical phrasing
     * (docker compose, REST endpoint shapes) while host-bound URLs, sensitive
     * route segments, secrets and stack traces stay banned. 'academic' and an
     * absent scope keep the strict isSafe() set. Mirrors the client guard in
     * assistant-output-guard.ts.
     */
    @Test
    void specializedScopeKeepsCorpusTechnicalPhrasingButBlocksMachinery() {
        String specializedLesson = "Bạn có thể dùng GitHub Actions, và chạy lệnh docker compose up -d --build khi push. "
                + "REST API trả về GET /api/v1/announcements cho danh sách thông báo.";

        assertTrue(AssistantOutputGuard.isSafeForScope(specializedLesson, "specialized"));
        assertFalse(AssistantOutputGuard.isSafeForScope(specializedLesson, "academic"));
        assertFalse(AssistantOutputGuard.isSafeForScope(specializedLesson, null));

        List<String> bannedInEveryScope = List.of(
                "Gọi https://api.campuscore.internal/api/v1/announcements trực tiếp.",
                "Endpoint nội bộ là /api/v1/assistant/chat.",
                "Endpoint nội bộ là /api/v1/thesis/assistant/chat.",
                "Cấu hình nằm trong /api/v1/admin/users.",
                "Mở /api/v1/mail để gửi thư.",
                "Lấy bearer token từ response trước.",
                "Chi tiết trong retrieved context và system prompt.",
                "Exception in thread \"main\" at io.campuscore.X(X.java:1)");
        for (String output : bannedInEveryScope) {
            assertFalse(AssistantOutputGuard.isSafeForScope(output, "specialized"), output);
        }
    }
}
