apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: campuscore-thesis-pilot

resources:
  - ../../base
  - thesis-service.yaml

patches:
  - path: patch-namespace.yaml
    target:
      kind: Namespace
      name: campuscore
  - path: patch-nginx-service.yaml
    target:
      kind: Service
      name: campuscore-nginx

configMapGenerator:
  - name: campuscore-nginx-thesis-pilot-config
    behavior: replace
    files:
      - thesis-pilot-upstream.conf
      - thesis-pilot-routes.conf

generatorOptions:
  disableNameSuffixHash: true
