package io.campuscore.restfulapi.auth;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.contains;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import io.campuscore.restfulapi.auth.repository.AuthUserRepository;
import io.campuscore.restfulapi.auth.service.AdminUserMutationService;
import io.campuscore.restfulapi.web.DomainException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.core.namedparam.SqlParameterSource;
import org.springframework.security.crypto.password.PasswordEncoder;

/**
 * The role ceiling has two halves and only one of them was reachable at first.
 *
 * <p>Refusing to <em>grant</em> a reserved role does not stop a plain
 * administrator from reaching the same powers through an account that already
 * holds one: resetting a dean's password hands out a working credential for that
 * dean, deleting the account removes the incumbent, and disabling it takes the
 * role out of service. None of those assigns a role, so a grant-side-only guard
 * leaves the escalation open — which an adversarial review demonstrated by
 * resetting a dean's password and signing in as them.
 *
 * <p>These tests deliberately assert that no state change occurred, not merely
 * that an exception was thrown: a guard that throws <em>after</em> mutating would
 * pass a status-only assertion while still leaking the credential. They also
 * drive the real service rather than a stubbed repository for that reason.
 *
 * <p>No real credential appears here; the temporary password is generated by the
 * service under test and is only ever handled as an opaque value.
 */
class AdminRoleCeilingTest {

    private static final String TARGET = "target-user-id";
    private static final String ACTOR = "actor-user-id";
    private static final String FACULTY_HEAD = "TRUONG_KHOA";

    private NamedParameterJdbcTemplate jdbc;
    private Map<String, Boolean> rolesTheTargetHolds;

    @BeforeEach
    void setUp() {
        jdbc = mock(NamedParameterJdbcTemplate.class);
        rolesTheTargetHolds = new HashMap<>();
        when(jdbc.queryForList(anyString(), any(MapSqlParameterSource.class), eq(Integer.class)))
                .thenAnswer(invocation -> {
                    MapSqlParameterSource parameters = invocation.getArgument(1);
                    String roleName = (String) parameters.getValue("roleName");
                    return Boolean.TRUE.equals(rolesTheTargetHolds.get(roleName)) ? List.of(1) : List.of();
                });
        when(jdbc.update(anyString(), any(SqlParameterSource.class))).thenReturn(1);
        when(jdbc.queryForObject(anyString(), any(MapSqlParameterSource.class), eq(String.class)))
                .thenReturn("ACTIVE");
    }

    private AdminUserMutationService service() {
        return new AdminUserMutationService(
                jdbc, mock(PasswordEncoder.class), mock(AuthUserRepository.class));
    }

    // ---------------------------------------------------------------- grant side

    @Test
    void plainAdminCannotMintAFacultyHeadButMayResubmitTheRoleUnchanged() {
        AdminUserMutationService service = service();

        DomainException denied = assertThrows(DomainException.class,
                () -> service.update(TARGET, Map.of("role", FACULTY_HEAD), false, ACTOR));
        assertThat(denied.getStatus()).isEqualTo(HttpStatus.FORBIDDEN);
        assertThat(denied.getCode()).isEqualTo("ROLE_ESCALATION");

        // The account already holds the role, so an edit form echoing it back is
        // not a grant. Later stages of update() may still fail for unrelated
        // reasons; what is asserted is that the escalation guard stays silent.
        rolesTheTargetHolds.put(FACULTY_HEAD, true);
        try {
            service.update(TARGET, Map.of("role", FACULTY_HEAD), false, ACTOR);
        } catch (DomainException unexpected) {
            assertNotEquals("ROLE_ESCALATION", unexpected.getCode(),
                    "re-sending the role an account already holds must not read as escalation");
        }
    }

    @Test
    void superAdminCanStillAssignTheFacultyHeadRole() {
        AdminUserMutationService service = service();

        try {
            service.update(TARGET, Map.of("role", FACULTY_HEAD), true, ACTOR);
        } catch (DomainException unexpected) {
            assertNotEquals("ROLE_ESCALATION", unexpected.getCode());
        }
    }

    // -------------------------------------------------------------- account side

    @Test
    void plainAdminCannotResetAFacultyHeadsPasswordAndNoCredentialIsIssued() {
        rolesTheTargetHolds.put(FACULTY_HEAD, true);
        AdminUserMutationService service = service();

        DomainException denied = assertThrows(DomainException.class,
                () -> service.resetPassword(TARGET, false, ACTOR));

        assertThat(denied.getStatus()).isEqualTo(HttpStatus.FORBIDDEN);
        assertThat(denied.getCode()).isEqualTo("ROLE_ESCALATION");
        // The whole point of the refusal: no working credential may have been minted
        // for the dean. A guard placed after the UPDATE would still pass a
        // status-only assertion, so assert the write never happened.
        verify(jdbc, never()).update(contains("SET \"password\""), any(SqlParameterSource.class));
    }

    @Test
    void plainAdminCannotDeleteAFacultyHeadAndTheRowSurvives() {
        rolesTheTargetHolds.put(FACULTY_HEAD, true);
        AdminUserMutationService service = service();

        DomainException denied = assertThrows(DomainException.class,
                () -> service.delete(TARGET, false, ACTOR));

        assertThat(denied.getStatus()).isEqualTo(HttpStatus.FORBIDDEN);
        verify(jdbc, never()).update(contains("DELETE FROM"), any(SqlParameterSource.class));
    }

    @Test
    void plainAdminCannotManageAFacultyHeadWithARoleLessUpdate() {
        rolesTheTargetHolds.put(FACULTY_HEAD, true);
        AdminUserMutationService service = service();

        DomainException denied = assertThrows(DomainException.class,
                () -> service.update(TARGET, Map.of("firstName", "Renamed"), false, ACTOR));

        assertThat(denied.getStatus()).isEqualTo(HttpStatus.FORBIDDEN);
    }

    @Test
    void plainAdminCannotDisableAFacultyHeadEvenWhenResendingTheUnchangedRole() {
        rolesTheTargetHolds.put(FACULTY_HEAD, true);
        AdminUserMutationService service = service();

        // Re-sending the unchanged role is permitted so unrelated fields stay
        // savable, but disabling the account is not an edit — it takes the role out
        // of service exactly as deleting it would.
        DomainException denied = assertThrows(DomainException.class, () -> service.update(
                TARGET, Map.of("role", FACULTY_HEAD, "status", "SUSPENDED"), false, ACTOR));

        assertThat(denied.getStatus()).isEqualTo(HttpStatus.FORBIDDEN);
        verify(jdbc, never()).update(contains("SET \"firstName\""), any(SqlParameterSource.class));
    }

    @Test
    void plainAdminStillCannotTakeOverAnAdminOrSuperAdminAccount() {
        for (String role : List.of("ADMIN", "SUPER_ADMIN")) {
            Map<String, Boolean> held = new HashMap<>();
            held.put(role, true);
            rolesTheTargetHolds = held;

            AdminUserMutationService service = service();
            assertThrows(DomainException.class, () -> service.resetPassword(TARGET, false, ACTOR));
            assertThrows(DomainException.class, () -> service.delete(TARGET, false, ACTOR));
        }
    }

    @Test
    void superAdminCanStillResetAndDeleteAFacultyHeadAccount() {
        rolesTheTargetHolds.put(FACULTY_HEAD, true);
        AdminUserMutationService service = service();

        service.resetPassword(TARGET, true, ACTOR);
        service.delete(TARGET, true, ACTOR);
    }

    @Test
    void superAdminCanStillResetADeanAccount() {
        rolesTheTargetHolds.put(FACULTY_HEAD, true);
        AdminUserMutationService service = service();

        try {
            service.resetPassword(TARGET, true, ACTOR);
        } catch (DomainException unexpected) {
            assertNotEquals("ROLE_ESCALATION", unexpected.getCode());
        }
    }

    // ---------------------------------------------------------- silent demotion

    @Test
    void blankRoleMeansNotSuppliedRatherThanDemoteToStudent() {
        rolesTheTargetHolds.put(FACULTY_HEAD, true);
        AdminUserMutationService service = service();

        // A client echoing an empty role back must not strip the dean's role. Before
        // the fix, a blank value fell through the "role == null" test and the text()
        // fallback turned it into STUDENT, silently demoting the account.
        DomainException denied = assertThrows(DomainException.class,
                () -> service.update(TARGET, Map.of("role", ""), false, ACTOR));

        // The blank is now treated as "no role supplied", so the protected-account
        // guard answers — not a role change to STUDENT.
        assertThat(denied.getCode()).isEqualTo("ROLE_ESCALATION");
        verify(jdbc, never()).update(contains("DELETE FROM"), any(SqlParameterSource.class));
    }

    @Test
    void blankRoleOnAnUnprotectedAccountIsTreatedAsNoRoleChange() {
        AdminUserMutationService service = service();

        try {
            service.update(TARGET, Map.of("role", ""), false, ACTOR);
        } catch (DomainException unexpected) {
            assertThat(unexpected.getCode())
                    .as("a blank role must not be read as an invalid role name")
                    .isNotEqualTo("ROLE_NOT_FOUND");
        }
    }
}
