apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: campuscore

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: campuscore

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.example.yaml
  - postgres.yaml
  - redis.yaml
  - rabbitmq.yaml
  - minio.yaml
  - core-api.yaml
  - auth-service.yaml
  - notification-service.yaml
  - finance-service.yaml
  - academic-service.yaml
  - engagement-service.yaml
  - people-service.yaml
  - analytics-service.yaml
  - frontend.yaml
  - nginx.yaml

configMapGenerator:
  - name: campuscore-nginx-config
    files:
      - nginx.conf
  - name: campuscore-nginx-thesis-pilot-config
    files:
      - thesis-pilot-upstream.conf
      - thesis-pilot-routes.conf

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: campuscore-backend
    newName: ghcr.io/jasontm17/campuscore-backend
    newTag: v1.4.1
  - name: campuscore-auth-service
    newName: ghcr.io/jasontm17/campuscore-auth-service
    newTag: v1.4.1
  - name: campuscore-notification-service
    newName: ghcr.io/jasontm17/campuscore-notification-service
    newTag: v1.4.1
  - name: campuscore-finance-service
    newName: ghcr.io/jasontm17/campuscore-finance-service
    newTag: v1.4.1
  - name: campuscore-academic-service
    newName: ghcr.io/jasontm17/campuscore-academic-service
    newTag: v1.4.1
  - name: campuscore-engagement-service
    newName: ghcr.io/jasontm17/campuscore-engagement-service
    newTag: v1.4.1
  - name: campuscore-people-service
    newName: ghcr.io/jasontm17/campuscore-people-service
    newTag: v1.4.1
  - name: campuscore-analytics-service
    newName: ghcr.io/jasontm17/campuscore-analytics-service
    newTag: v1.4.1
  - name: campuscore-frontend
    newName: ghcr.io/jasontm17/campuscore-frontend
    newTag: v1.4.1
