import type { Lecturer } from '@/types/api';

/**
 * Seeded HCMUTE Thesis Advisors & Faculty Directory.
 * Matches V32__enrich_big_data_campus_ecosystem.sql academic ecosystem.
 * Used as reliable faculty directory for student thesis advisor discovery and proposal.
 */
export const FALLBACK_THESIS_ADVISORS: Lecturer[] = [
  {
    id: 'lecturer-profile-023',
    userId: 'lecturer-user-023',
    departmentId: 'department-demo',
    employeeId: 'LEC-DEMO-023',
    title: 'PGS.TS.',
    specialization: 'Hệ thống Dữ liệu lớn (Big Data) và Học máy ứng dụng',
    office: 'A1-402',
    phone: '028-3722-1201',
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    user: {
      id: 'lecturer-user-023',
      email: 'sang.ht@campuscore.demo',
      firstName: 'Sang',
      lastName: 'Huỳnh Thanh',
      status: 'ACTIVE',
      createdAt: '2026-01-01T00:00:00Z',
    },
  },
  {
    id: 'lecturer-profile-024',
    userId: 'lecturer-user-024',
    departmentId: 'department-demo',
    employeeId: 'LEC-DEMO-024',
    title: 'TS.',
    specialization: 'Trí tuệ Nhân tạo, Thị giác máy tính và Xử lý ảnh y tế',
    office: 'A1-405',
    phone: '028-3722-1202',
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    user: {
      id: 'lecturer-user-024',
      email: 'thong.cm@campuscore.demo',
      firstName: 'Thông',
      lastName: 'Cao Minh',
      status: 'ACTIVE',
      createdAt: '2026-01-01T00:00:00Z',
    },
  },
  {
    id: 'lecturer-profile-025',
    userId: 'lecturer-user-025',
    departmentId: 'department-demo',
    employeeId: 'LEC-DEMO-025',
    title: 'ThS.',
    specialization: 'An ninh mạng, Mật mã học và Hệ thống phân tán',
    office: 'A1-408',
    phone: '028-3722-1203',
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    user: {
      id: 'lecturer-user-025',
      email: 'nguyet.lta@campuscore.demo',
      firstName: 'Nguyệt',
      lastName: 'Lê Thị Ánh',
      status: 'ACTIVE',
      createdAt: '2026-01-01T00:00:00Z',
    },
  },
  {
    id: 'lecturer-profile-013',
    userId: 'lecturer-user-013',
    departmentId: 'department-feee-auto',
    employeeId: 'LEC-DEMO-013',
    title: 'PGS.TS.',
    specialization: 'Điều khiển tự động và Hệ thống nhúng công nghiệp',
    office: 'B1-201',
    phone: '028-3722-1204',
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    user: {
      id: 'lecturer-user-013',
      email: 'tuan.tq@campuscore.demo',
      firstName: 'Tuấn',
      lastName: 'Trịnh Quốc',
      status: 'ACTIVE',
      createdAt: '2026-01-01T00:00:00Z',
    },
  },
  {
    id: 'lecturer-profile-014',
    userId: 'lecturer-user-014',
    departmentId: 'department-feee-telecom',
    employeeId: 'LEC-DEMO-014',
    title: 'TS.',
    specialization: 'Truyền thông không dây 5G/6G và Mạng cảm biến IoT',
    office: 'B1-205',
    phone: '028-3722-1205',
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    user: {
      id: 'lecturer-user-014',
      email: 'nam.lh@campuscore.demo',
      firstName: 'Nam',
      lastName: 'Lê Hoàng',
      status: 'ACTIVE',
      createdAt: '2026-01-01T00:00:00Z',
    },
  },
  {
    id: 'lecturer-profile-016',
    userId: 'lecturer-user-016',
    departmentId: 'department-fme-robotics',
    employeeId: 'LEC-DEMO-016',
    title: 'PGS.TS.',
    specialization: 'Robot công nghiệp và Cơ điện tử thông minh',
    office: 'C2-102',
    phone: '028-3722-1301',
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    user: {
      id: 'lecturer-user-016',
      email: 'hung.nv@campuscore.demo',
      firstName: 'Hùng',
      lastName: 'Nguyễn Văn',
      status: 'ACTIVE',
      createdAt: '2026-01-01T00:00:00Z',
    },
  },
  {
    id: 'lecturer-profile-017',
    userId: 'lecturer-user-017',
    departmentId: 'department-fme-automotive',
    employeeId: 'LEC-DEMO-017',
    title: 'TS.',
    specialization: 'Hệ thống truyền lực xe điện và Xe tự hành',
    office: 'E2-101',
    phone: '028-3722-1302',
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    user: {
      id: 'lecturer-user-017',
      email: 'khang.vm@campuscore.demo',
      firstName: 'Khang',
      lastName: 'Võ Minh',
      status: 'ACTIVE',
      createdAt: '2026-01-01T00:00:00Z',
    },
  },
  {
    id: 'lecturer-profile-019',
    userId: 'lecturer-user-019',
    departmentId: 'department-foe-mis',
    employeeId: 'LEC-DEMO-019',
    title: 'TS.',
    specialization: 'Hệ thống ERP, Khai phá dữ liệu kinh doanh và TMĐT',
    office: 'A1-301',
    phone: '028-3722-1401',
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    user: {
      id: 'lecturer-user-019',
      email: 'linh.ptd@campuscore.demo',
      firstName: 'Linh',
      lastName: 'Phan Thị Diệu',
      status: 'ACTIVE',
      createdAt: '2026-01-01T00:00:00Z',
    },
  },
  {
    id: 'lecturer-profile-020',
    userId: 'lecturer-user-020',
    departmentId: 'department-foe-finance',
    employeeId: 'LEC-DEMO-020',
    title: 'ThS.',
    specialization: 'FinTech, Định lượng tài chính và Quản trị rủi ro',
    office: 'A1-305',
    phone: '028-3722-1402',
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    user: {
      id: 'lecturer-user-020',
      email: 'tan.nn@campuscore.demo',
      firstName: 'Tân',
      lastName: 'Nguyễn Ngọc',
      status: 'ACTIVE',
      createdAt: '2026-01-01T00:00:00Z',
    },
  },
  {
    id: 'lecturer-profile-022',
    userId: 'lecturer-user-022',
    departmentId: 'department-fce-civil',
    employeeId: 'LEC-DEMO-022',
    title: 'TS.',
    specialization: 'Kết cấu công trình, BIM và Quản lý dự án xây dựng',
    office: 'D1-102',
    phone: '028-3722-1601',
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    user: {
      id: 'lecturer-user-022',
      email: 'long.dv@campuscore.demo',
      firstName: 'Long',
      lastName: 'Đoàn Văn',
      status: 'ACTIVE',
      createdAt: '2026-01-01T00:00:00Z',
    },
  },
];
